# Generated by Django 6.0.1 on 2026-01-25 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipementNumerique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026, verbose_name="Année")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("nom", models.CharField(max_length=100, verbose_name="Nom / Service")),
                (
                    "type_equipement",
                    models.CharField(
                        choices=[
                            (
                                "1. Hardware (Terminaux)",
                                [
                                    ("LAPTOP", "Ordinateur Portable (250kg CO2e)"),
                                    (
                                        "DESKTOP_SCREEN",
                                        "Ordinateur Fixe + Écran (350kg CO2e)",
                                    ),
                                    ("SMARTPHONE", "Smartphone / Tablette (50kg CO2e)"),
                                ],
                            ),
                            (
                                "2. Réseau",
                                [
                                    ("BORNE_WIFI", "Borne Wi-Fi (20kg CO2e)"),
                                    ("SWITCH", "Switch réseau (80kg CO2e)"),
                                ],
                            ),
                            (
                                "3. Cloud & Services",
                                [
                                    (
                                        "CLOUD_INSTANCE",
                                        "Instance Cloud / Serveur virtuel (500kg CO2e)",
                                    ),
                                    (
                                        "CLOUD_STORAGE",
                                        "Stockage Cloud 1 To (150kg CO2e)",
                                    ),
                                ],
                            ),
                            (
                                "4. Périphériques",
                                [
                                    ("PRINTER", "Imprimante Laser (500kg CO2e)"),
                                    (
                                        "SCREEN_EXTRA",
                                        "Écran supplémentaire (200kg CO2e)",
                                    ),
                                ],
                            ),
                        ],
                        max_length=30,
                        verbose_name="Type d'équipement",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "duree_vie",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Durée de vie (ans)"
                    ),
                ),
                (
                    "empreinte_fabrication",
                    models.FloatField(
                        default=0,
                        editable=False,
                        help_text="Total fabrication (non amorti)",
                    ),
                ),
                (
                    "consommation_annuelle",
                    models.FloatField(
                        default=0, editable=False, help_text="kWh par an"
                    ),
                ),
                (
                    "total_co2_kg",
                    models.FloatField(
                        default=0,
                        editable=False,
                        help_text="Empreinte annuelle amortie + Usage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
