# Generated by Django 6.0.1 on 2026-01-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("numerique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueEmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_equipement",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code Type"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "fabrication_kg_co2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Empreinte fabrication (kg CO2e)",
                        max_digits=10,
                    ),
                ),
                (
                    "conso_kwh_an",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Conso électrique annuelle moyenne (kWh)",
                        max_digits=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="Base Empreinte® ADEME 2024", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur Émission Numérique",
                "verbose_name_plural": "Facteurs Émission Numérique",
            },
        ),
        migrations.RemoveField(
            model_name="equipementnumerique",
            name="group",
        ),
        migrations.AddField(
            model_name="equipementnumerique",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipementnumerique",
            name="type_equipement",
            field=models.CharField(
                choices=[
                    (
                        "1. Hardware (Terminaux)",
                        [
                            ("LAPTOP", "Ordinateur Portable"),
                            ("DESKTOP_SCREEN", "Ordinateur Fixe + Écran"),
                            ("SMARTPHONE", "Smartphone / Tablette"),
                        ],
                    ),
                    (
                        "2. Réseau",
                        [("BORNE_WIFI", "Borne Wi-Fi"), ("SWITCH", "Switch réseau")],
                    ),
                    (
                        "3. Cloud & Services",
                        [
                            ("CLOUD_INSTANCE", "Instance Cloud / Serveur virtuel"),
                            ("CLOUD_STORAGE", "Stockage Cloud 1 To"),
                        ],
                    ),
                    (
                        "4. Périphériques",
                        [
                            ("PRINTER", "Imprimante Laser"),
                            ("SCREEN_EXTRA", "Écran supplémentaire"),
                        ],
                    ),
                ],
                max_length=30,
                verbose_name="Type d'équipement",
            ),
        ),
    ]
