# Generated by Django 6.0.1 on 2026-01-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("numerique", "0003_equipementnumerique_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="numeriqueemissionfactor",
            name="source",
            field=models.CharField(blank=True, default="ADEME", max_length=200),
        ),
    ]
