# Generated by Django 6.0.1 on 2026-01-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessageSensibilisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(default="Le mot de la Mairie", max_length=200),
                ),
                (
                    "contenu",
                    models.TextField(
                        help_text="Le message à afficher sur le tableau de bord."
                    ),
                ),
                (
                    "type_message",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("CONSEIL", "Conseil"),
                            ("ALERTE", "Alerte"),
                            ("OBJECTIF", "Objectif"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                (
                    "actif",
                    models.BooleanField(
                        default=True,
                        help_text="Cochez pour afficher ce message sur le dashboard.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message de Sensibilisation",
                "verbose_name_plural": "Messages de Sensibilisation",
                "ordering": ["-created_at"],
            },
        ),
    ]
