# Generated by Django 6.0.1 on 2026-01-26 12:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodEmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                (
                    "kg_co2_per_meal",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="ADEME Base Carbone / Agribalyse", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur d'émission repas",
                "verbose_name_plural": "Facteurs d'émission repas",
            },
        ),
        migrations.CreateModel(
            name="FoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service", models.CharField(max_length=150)),
                (
                    "year",
                    models.IntegerField(
                        choices=[
                            (2020, 2020),
                            (2021, 2021),
                            (2022, 2022),
                            (2023, 2023),
                            (2024, 2024),
                            (2025, 2025),
                            (2026, 2026),
                            (2027, 2027),
                            (2028, 2028),
                            (2029, 2029),
                            (2030, 2030),
                            (2031, 2031),
                            (2032, 2032),
                            (2033, 2033),
                            (2034, 2034),
                            (2035, 2035),
                        ]
                    ),
                ),
                (
                    "beef_meals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Repas bœuf/veau"
                    ),
                ),
                (
                    "pork_meals",
                    models.PositiveIntegerField(default=0, verbose_name="Repas porc"),
                ),
                (
                    "poultry_fish_meals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Repas poulet/poisson"
                    ),
                ),
                (
                    "vegetarian_meals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Repas végétariens"
                    ),
                ),
                (
                    "picnic_no_meat_meals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pique-niques sans viande"
                    ),
                ),
                (
                    "picnic_meat_meals",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Pique-niques avec viande"
                    ),
                ),
                (
                    "total_co2_kg",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée alimentation",
                "verbose_name_plural": "Données alimentation",
                "ordering": ["-year", "service"],
                "unique_together": {("group", "service", "year")},
            },
        ),
    ]
