# Generated by Django 6.0.1 on 2026-01-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foodemissionfactor",
            options={
                "verbose_name": "Facteur Émission Alimentation",
                "verbose_name_plural": "Facteurs Émission Alimentation",
            },
        ),
        migrations.AlterUniqueTogether(
            name="foodentry",
            unique_together={("service", "year")},
        ),
        migrations.AddField(
            model_name="foodentry",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="foodentry",
            name="group",
        ),
    ]
