# Generated by Django 6.0.1 on 2026-01-27 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alimentation", "0003_foodentry_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodemissionfactor",
            name="source",
            field=models.CharField(default="ADEME", max_length=200),
        ),
    ]
