# Generated by Django 6.0.1 on 2026-01-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseEmissionFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, unique=True, verbose_name='Code catégorie')),
                ('category_label', models.CharField(max_length=200, verbose_name='Libellé catégorie')),
                ('factor_kg_co2_per_keur', models.DecimalField(decimal_places=2, help_text="kg CO2e par millier d'euros dépensés", max_digits=8, verbose_name="Facteur d'émission (kgCO2e/k€)")),
                ('source', models.CharField(default='Excel Achats 30% - ADEME', max_length=300, verbose_name='Source')),
            ],
            options={
                'verbose_name': "Facteur d'émission achat",
                'verbose_name_plural': "Facteurs d'émission achats",
                'ordering': ['category_label'],
            },
        ),
        migrations.AlterField(
            model_name='purchasedata',
            name='emission_factor',
            field=models.DecimalField(decimal_places=2, help_text='Facteur automatique selon la catégorie', max_digits=8, verbose_name="Facteur d'émission (kgCO2e/k€)"),
        ),
    ]
