# Generated by Django 6.0.1 on 2026-01-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ADEMEConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "csv_url",
                    models.URLField(
                        default="https://data.ademe.fr/data-fair/api/v1/datasets/base-carboner/data-files/Base_Carbone_V23.6.csv",
                        help_text="URL officielle du fichier CSV Base Carbone de l'ADEME",
                        max_length=500,
                        verbose_name="URL du fichier CSV ADEME",
                    ),
                ),
                (
                    "update_frequency_months",
                    models.IntegerField(
                        default=6,
                        help_text="Nombre de mois entre deux mises à jour automatiques",
                        verbose_name="Fréquence de mise à jour (mois)",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date et heure de la dernière mise à jour réussie",
                        null=True,
                        verbose_name="Dernière mise à jour",
                    ),
                ),
                (
                    "csv_version",
                    models.CharField(
                        blank=True,
                        help_text="Version du CSV ADEME actuellement utilisée (ex: V23.6)",
                        max_length=50,
                        verbose_name="Version du CSV",
                    ),
                ),
                (
                    "notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email pour recevoir les notifications de mise à jour",
                        max_length=254,
                        verbose_name="Email de notification",
                    ),
                ),
                (
                    "enable_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="Envoyer un email après chaque mise à jour",
                        verbose_name="Activer les notifications",
                    ),
                ),
                (
                    "active_sectors",
                    models.JSONField(
                        default=list,
                        help_text="Liste des secteurs pour lesquels importer les facteurs d'émission",
                        verbose_name="Secteurs actifs",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration ADEME",
                "verbose_name_plural": "Configuration ADEME",
            },
        ),
    ]
