# Generated by Django 6.0.1 on 2026-01-28 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserManual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Guide Utilisateur",
                        max_length=200,
                        verbose_name="Titre du guide",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Code HTML du manuel. Vous pouvez utiliser des balises <h3>, <p>, <ul>, <li>, etc.",
                        verbose_name="Contenu HTML",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "group",
                    models.OneToOneField(
                        blank=True,
                        help_text="Si vide, ce manuel sera le guide par défaut pour tous.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="auth.group",
                        verbose_name="Groupe cible",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuel Utilisateur",
                "verbose_name_plural": "Manuels Utilisateurs",
                "ordering": ["group__name"],
            },
        ),
    ]
