# Generated by Django 6.0.1 on 2026-01-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_usermanual"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReminderTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        default="Rappel - Saisie du bilan carbone {year}",
                        max_length=200,
                        verbose_name="Sujet de l'email",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        default="Bonjour {user},\n\nC'est le moment de saisir vos données pour le bilan carbone {year} de la Mairie d'Évry-Courcouronnes.\n\n📊 Accédez au tableau de bord : {url}\n\nMerci de saisir vos consommations énergétiques et déplacements professionnels dans les meilleurs délais.\n\nCordialement,\nL'équipe Bilan Carbone",
                        help_text="Variables disponibles : {user} (nom), {year} (année), {url} (lien dashboard).",
                        verbose_name="Corps du message",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Modèle d'Email de Rappel",
                "verbose_name_plural": "Modèles d'Email de Rappel",
            },
        ),
    ]
