# Generated by Django 6.0.1 on 2026-01-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="Année")),
                (
                    "site_name",
                    models.CharField(
                        default="Site inconnu",
                        max_length=200,
                        verbose_name="Nom du site",
                    ),
                ),
                (
                    "surface_area",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="m²",
                        max_digits=10,
                        verbose_name="Surface (m²)",
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Année de construction"
                    ),
                ),
                (
                    "electricity_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Électricité (kWh)",
                    ),
                ),
                (
                    "gas_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gaz Naturel (kWh)",
                    ),
                ),
                (
                    "heating_network_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Réseau de chaleur (kWh)",
                    ),
                ),
                (
                    "cooling_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Climatisation (kWh)",
                    ),
                ),
                (
                    "photovoltaic_production_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Production PV (kWh)",
                    ),
                ),
                (
                    "electricity_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "gas_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "heating_network_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "cooling_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "total_co2_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée bâtiment",
                "verbose_name_plural": "Données bâtiment",
                "ordering": ["-year", "-created_at"],
            },
        ),
    ]
