# Generated by Django 6.0.1 on 2026-01-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batiment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="buildingenergydata",
            name="construction_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Année de construction"
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="cooling_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Climatisation (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="electricity_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Électricité (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="gas_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Gaz Naturel (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="heating_network_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Réseau de chaleur (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Notes"),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="photovoltaic_production_kwh",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Production PV (kWh)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="site_name",
            field=models.CharField(
                default="Site inconnu", max_length=200, verbose_name="Nom du site"
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="surface_area",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="m²",
                max_digits=10,
                verbose_name="Surface (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="buildingenergydata",
            name="year",
            field=models.PositiveIntegerField(verbose_name="Année"),
        ),
    ]
