# Generated by Django 6.0.1 on 2026-01-22 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEnergyData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("site_name", models.CharField(default="Site inconnu", max_length=200)),
                (
                    "surface_area",
                    models.DecimalField(
                        decimal_places=2, default=0, help_text="m²", max_digits=10
                    ),
                ),
                (
                    "construction_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "electricity_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "gas_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "heating_network_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cooling_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "photovoltaic_production_kwh",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "electricity_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "gas_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "heating_network_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "cooling_factor",
                    models.DecimalField(decimal_places=6, default=0, max_digits=10),
                ),
                (
                    "total_co2_kg",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
