# Generated by Django 6.0.1 on 2026-01-25 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batiment", "0002_alter_buildingenergydata_construction_year_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="buildingenergydata",
            options={
                "ordering": ["-year", "-created_at"],
                "verbose_name": "Donnée bâtiment",
                "verbose_name_plural": "Données bâtiment",
            },
        ),
    ]
