# Generated by Django 6.0.1 on 2026-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batiment", "0003_alter_buildingenergydata_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BuildingEmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_energie",
                    models.CharField(
                        choices=[
                            ("ELEC", "Électricité"),
                            ("GAZ", "Gaz Naturel"),
                            ("HEAT", "Réseau de chaleur"),
                            ("COOL", "Climatisation"),
                        ],
                        max_length=10,
                        unique=True,
                        verbose_name="Type d'énergie",
                    ),
                ),
                (
                    "facteur",
                    models.DecimalField(
                        decimal_places=6, help_text="kgCO2e/kWh", max_digits=10
                    ),
                ),
                ("unit", models.CharField(default="kgCO2e/kWh", max_length=20)),
                (
                    "source",
                    models.CharField(blank=True, default="ADEME", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Facteur Émission Bâtiment",
                "verbose_name_plural": "Facteurs Émission Bâtiment",
            },
        ),
    ]
