# Generated by Django 6.0.1 on 2026-01-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0002_vehicledata_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emissionfactor",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Facteur Émission Véhicules",
                "verbose_name_plural": "Facteurs Émission Véhicules",
            },
        ),
        migrations.AlterModelOptions(
            name="vehicledata",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Donnée véhicule",
                "verbose_name_plural": "Données véhicules",
            },
        ),
        migrations.AlterUniqueTogether(
            name="vehicledata",
            unique_together={("user", "year", "service")},
        ),
        migrations.AlterField(
            model_name="vehicledata",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="vehicledata",
            name="group",
        ),
    ]
