# Generated by Django 6.0.1 on 2026-01-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("numerique", "0002_equipementnumerique_marque_modele"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumeriqueEmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_equipement",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code Type"
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Libellé")),
                (
                    "fabrication_kg_co2",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Empreinte fabrication (kg CO2e)",
                        max_digits=10,
                    ),
                ),
                (
                    "conso_kwh_an",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Conso électrique annuelle moyenne (kWh)",
                        max_digits=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, default="Base Empreinte® ADEME 2024", max_length=200
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur Émission Numérique",
                "verbose_name_plural": "Facteurs Émission Numérique",
            },
        ),
        migrations.AlterModelOptions(
            name="equipementnumerique",
            options={
                "ordering": ["-year", "-created_at"],
                "verbose_name": "Équipement numérique",
                "verbose_name_plural": "Données numérique",
            },
        ),
    ]
