# Generated by Django 6.0.1 on 2026-01-22 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Année')),
                ('service', models.CharField(blank=True, help_text='Service ou direction concerné', max_length=200, verbose_name='Service/Direction')),
                ('category', models.CharField(choices=[('food_service', 'Restauration & Services légers'), ('insurance', 'Assurances & Cotisations'), ('it_telecom', 'IT & Téléphonie'), ('cleaning_maintenance', 'Nettoyage & Entretien & Espaces verts'), ('activities', 'Séjours & Activités'), ('laundry', 'Blanchisserie'), ('construction', 'Travaux & Construction'), ('transport', 'Transports'), ('equipment_rental', 'Location équipements')], max_length=50, verbose_name="Catégorie d'achat")),
                ('description', models.CharField(help_text='Description détaillée du marché ou service', max_length=500, verbose_name='Description du marché/service')),
                ('amount_euros', models.DecimalField(decimal_places=2, help_text='Montant total en euros', max_digits=12, verbose_name='Montant (€)')),
                ('emission_factor', models.DecimalField(decimal_places=2, help_text='Facteur automatique selon la catégorie', max_digits=6, verbose_name="Facteur d'émission (kgCO2e/k€)")),
                ('total_co2_kg', models.DecimalField(decimal_places=2, help_text='Impact carbone total calculé', max_digits=12, verbose_name='Total CO₂ (kg)')),
                ('notes', models.TextField(blank=True, help_text='Notes ou commentaires additionnels', verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Donnée d'achat",
                'verbose_name_plural': "Données d'achats",
                'ordering': ['-created_at'],
            },
        ),
    ]
