# Generated by Django 6.0.1 on 2026-01-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseEmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Code catégorie"
                    ),
                ),
                (
                    "category_label",
                    models.CharField(max_length=200, verbose_name="Libellé catégorie"),
                ),
                (
                    "factor_kg_co2_per_keur",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="kg CO2e par millier d'euros dépensés",
                        max_digits=8,
                        verbose_name="Facteur d'émission (kgCO2e/k€)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        default="Excel Achats 30% - ADEME",
                        max_length=300,
                        verbose_name="Source",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facteur d'émission achat",
                "verbose_name_plural": "Facteurs d'émission achats",
                "ordering": ["category_label"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(default=2026, verbose_name="Année")),
                (
                    "service",
                    models.CharField(
                        blank=True,
                        help_text="Service ou direction concerné",
                        max_length=200,
                        verbose_name="Service/Direction",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food_service", "Restauration & Services légers"),
                            ("insurance", "Assurances & Cotisations"),
                            ("it_telecom", "IT & Téléphonie"),
                            (
                                "cleaning_maintenance",
                                "Nettoyage & Entretien & Espaces verts",
                            ),
                            ("activities", "Séjours & Activités"),
                            ("laundry", "Blanchisserie"),
                            ("construction", "Travaux & Construction"),
                            ("transport", "Transports"),
                            ("equipment_rental", "Location équipements"),
                        ],
                        max_length=50,
                        verbose_name="Catégorie d'achat",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description détaillée du marché ou service",
                        max_length=500,
                        verbose_name="Description du marché/service",
                    ),
                ),
                (
                    "amount_euros",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant total en euros",
                        max_digits=12,
                        verbose_name="Montant (€)",
                    ),
                ),
                (
                    "emission_factor",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Facteur automatique selon la catégorie",
                        max_digits=8,
                        verbose_name="Facteur d'émission (kgCO2e/k€)",
                    ),
                ),
                (
                    "total_co2_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Impact carbone total calculé",
                        max_digits=12,
                        verbose_name="Total CO₂ (kg)",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes ou commentaires additionnels",
                        verbose_name="Notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière modification"
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                        verbose_name="Groupe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donnée d'achat",
                "verbose_name_plural": "Données d'achats",
                "ordering": ["-created_at"],
            },
        ),
    ]
