# Generated by Django 6.0.1 on 2026-01-27 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseemissionfactor",
            options={
                "ordering": ["category_label"],
                "verbose_name": "Facteur Émission Achats",
                "verbose_name_plural": "Facteurs Émission Achats",
            },
        ),
        migrations.RemoveField(
            model_name="purchasedata",
            name="group",
        ),
        migrations.AddField(
            model_name="purchasedata",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
            preserve_default=False,
        ),
    ]
