# Generated by Django 6.0.1 on 2026-01-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0004_alter_purchaseemissionfactor_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedata",
            name="category",
            field=models.CharField(
                choices=[
                    ("food_service", "Restauration & Services légers"),
                    ("insurance", "Assurances & Cotisations"),
                    ("cleaning_maintenance", "Nettoyage & Entretien & Espaces verts"),
                    ("activities", "Séjours & Activités"),
                    ("laundry", "Blanchisserie"),
                    ("construction", "Travaux & Construction"),
                    ("transport", "Transports"),
                    ("equipment_rental", "Location équipements"),
                ],
                max_length=50,
                verbose_name="Catégorie d'achat",
            ),
        ),
    ]
