# Generated by Django 6.0.1 on 2026-01-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensibilisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="messagesensibilisation",
            name="type_contenu",
            field=models.CharField(
                choices=[
                    ("message", "Message / Conseil"),
                    ("zoom", "Zoom sur une Action"),
                ],
                default="message",
                help_text="Message = conseil général, Zoom = action spécifique à mettre en avant",
                max_length=20,
                verbose_name="Type de contenu",
            ),
        ),
    ]
